n = int(input(" введите целое число: "))
print(n)
m = str(input(" введите слово: "))
print(m)
c = float(input(" введите дробное число: "))
print(c)
v = int(input(" введите ваш возраст: "))
b = str(input("введите ваше имя: "))
print("Возраст: ", v, ".", "Имя: ", b)
